const questionBank = {
    dbms: [
        { q: "What is a DBMS?", options: ["A software to managing databases", "A hardware component", "A programming language", "A file system"], answer: 0 },
        { q: "Which constraint ensures unique values in a column?", options: ["NOT NULL", "UNIQUE", "DEFAULT", "CHECK"], answer: 1 },
        { q: "What defines a Primary Key?", options: ["A foreign element", "A null value allowed column", "A unique identifier for a record", "A string data type"], answer: 2 },
        { q: "The main purpose of database normalization is to:", options: ["Increase database size", "Reduce data redundancy", "Eliminate tables", "Increase data redundancy"], answer: 1 },
        { q: "DML stands for:", options: ["Data Manipulation Language", "Data Mining Language", "Data Definition Language", "Data Control Language"], answer: 0 },
        { q: "Which of the following is NOT a NoSQL database?", options: ["MongoDB", "Cassandra", "MySQL", "Redis"], answer: 2 },
        { q: "What is an Entity in DBMS?", options: ["A table", "A real-world object", "A relationship", "An attribute"], answer: 1 },
        { q: "A primary key combined with a foreign key creates a:", options: ["Candidate Key", "Super Key", "Relationship", "Composite Key"], answer: 2 },
        { q: "Which SQL command is used to remove all records from a table?", options: ["DELETE", "REMOVE", "DROP", "TRUNCATE"], answer: 3 },
        { q: "What is ACID property in DBMS?", options: ["Atomicity, Consistency, Isolation, Durability", "Atomicity, Concurrency, Isolation, Durability", "Access, Consistency, Integrity, Durability", "Action, Consistency, isolation, Distribution"], answer: 0 },
        { q: "Which level of abstraction describes how data is stored?", options: ["Physical level", "Logical level", "View level", "Conceptual level"], answer: 0 },
        { q: "What is a Join in SQL?", options: ["Combining tables based on a related column", "Merging two databases", "Deleting duplicate records", "Sorting data in a table"], answer: 0 },
        { q: "What is a View?", options: ["A virtual table", "A physical table", "A database backup", "A query"], answer: 0 },
        { q: "Which command is used to change data in a table?", options: ["CHANGE", "MODIFY", "UPDATE", "ALTER"], answer: 2 },
        { q: "What is a Surrogate Key?", options: ["A key with business meaning", "An artificial key", "A foreign key", "A primary key"], answer: 1 },
        { q: "What is a Deadlock in DBMS?", options: ["Two processes waiting for each other", "A system crash", "A data corruption", "A slow query"], answer: 0 },
        { q: "Which SQL clause is used to filter group results?", options: ["WHERE", "ORDER BY", "HAVING", "GROUP BY"], answer: 2 },
        { q: "What is a Trigger?", options: ["A stored procedure", "An automatic action on table event", "A query optimizer", "A backup tool"], answer: 1 },
        { q: "What is Denormalization?", options: ["Increasing redundancy for performance", "Removing all tables", "Splitting tables", "Adding more constraints"], answer: 0 },
        { q: "Which normal form deals with multi-valued dependencies?", options: ["1NF", "2NF", "3NF", "4NF"], answer: 3 },
        { q: "What is a B-Tree?", options: ["A sorting algorithm", "A self-balancing search tree used in indexing", "A data structure for hashing", "A graph"], answer: 1 },
        { q: "What is a Foreign Key?", options: ["A key from another table", "A primary key", "A unique key", "A candidate key"], answer: 0 },
        { q: "What is a Schema?", options: ["A data record", "The structural description of a database", "A query", "A database user"], answer: 1 },
        { q: "Which SQL command is used to add a column to a table?", options: ["INSERT", "UPDATE", "ALTER TABLE", "CREATE"], answer: 2 },
        { q: "What is the result of a Cartesian Product?", options: ["Intersection of two tables", "Union of two tables", "All possible combinations of rows", "Difference of two tables"], answer: 2 },
        { q: "What is Redundancy?", options: ["Data security", "Data duplication", "Data integrity", "Data consistency"], answer: 1 },
        { q: "What is a Candidate Key?", options: ["Any key that can be a primary key", "The primary key itself", "A foreign key", "A non-unique key"], answer: 0 },
        { q: "Which operator is used for pattern matching in SQL?", options: ["MATCH", "LIKE", "EQUAL", "SEARCH"], answer: 1 },
        { q: "What is an Index?", options: ["A way to speed up data retrieval", "A table backup", "A primary key", "A data constraint"], answer: 0 },
        { q: "What is Write Ahead Logging (WAL)?", options: ["A backup strategy", "A technique for ensuring atomicity and durability", "A data compression method", "A query optimization technique"], answer: 1 }
    ],
    oops: [
        { q: "What is Inheritance in OOPS?", options: ["Hiding implementation details", "Acquiring properties of another class", "Binding data and functions", "Creating multiple functions"], answer: 1 },
        { q: "Encapsulation primarily deals with:", options: ["Code reuse", "Multiple inheritance", "Data hiding", "Method Overloading"], answer: 2 },
        { q: "Polymorphism means:", options: ["Hiding forms", "One form", "Many forms", "No forms"], answer: 2 },
        { q: "Which of the following is NOT a core OOPS concept?", options: ["Compilation", "Abstraction", "Inheritance", "Encapsulation"], answer: 0 },
        { q: "What is a Class?", options: ["An instance of an object", "A blueprint for creating objects", "A functional pointer", "A variable"], answer: 1 },
        { q: "What is an Object?", options: ["A Blueprint", "A Function", "A Method", "An instance of a class"], answer: 3 },
        { q: "Which keyword is used to inherit a class in Java?", options: ["implements", "extends", "inherits", "using"], answer: 1 },
        { q: "What is an Abstract Class?", options: ["A class that cannot be instantiated", "A class with only static methods", "A class that is hidden", "A class with no methods"], answer: 0 },
        { q: "What is an Interface?", options: ["A contract for classes", "A type of class", "A variable", "A loop"], answer: 0 },
        { q: "What is Method Overloading?", options: ["Redefining a method in a subclass", "Multiple methods with same name but different parameters", "A method that calls itself", "Hiding a method"], answer: 1 },
        { q: "What is Method Overriding?", options: ["Redefining a method in a subclass", "Multiple methods with same name", "Hiding data", "A type of polymorphism"], answer: 0 },
        { q: "What is a Constructor?", options: ["A method to create objects", "A method to delete objects", "A special method to initialize objects", "A variable type"], answer: 2 },
        { q: "What is a Destructor?", options: ["A method to create objects", "A method to clean up/destroy objects", "A loop", "A conditional statement"], answer: 1 },
        { q: "What is the 'this' keyword used for?", options: ["Referring to the superclass", "Referring to the current instance", "Referring to a static method", "Creating a new object"], answer: 1 },
        { q: "What is a Static Member?", options: ["A member belonging to the class rather than an instance", "A constant value", "A private member", "A hidden member"], answer: 0 },
        { q: "What are Access Modifiers?", options: ["Keywords that define visibility of classes and members", "Loops", "Variable types", "Compiler flags"], answer: 0 },
        { q: "Which access modifier gives the most restrictive access?", options: ["Public", "Protected", "Default", "Private"], answer: 3 },
        { q: "What is Composition?", options: ["A class containing an instance of another class", "Inheriting from multiple classes", "Binding data", "Hiding logic"], answer: 0 },
        { q: "What is an Inner Class?", options: ["A class defined inside another class", "A class with no name", "A hidden class", "A static class"], answer: 0 },
        { q: "What is a Virtual Function?", options: ["A function that can be overridden", "A function that has no body", "A private function", "A static function"], answer: 0 },
        { q: "What is Early Binding?", options: ["Method resolved at runtime", "Method resolved at compile time", "Dynamic dispatch", "Late binding"], answer: 1 },
        { q: "What is Late Binding?", options: ["Method resolved at compile time", "Method resolved at runtime", "Static binding", "Pre-compilation"], answer: 1 },
        { q: "What is Multiple Inheritance?", options: ["A class inheriting from more than one class", "A class having multiple methods", "One class inherited by many", "A type of polymorphism"], answer: 0 },
        { q: "What is Multilevel Inheritance?", options: ["Inheriting from a class which is also inherited", "Inheriting from multiple classes", "Hiding methods", "Binary inheritance"], answer: 0 },
        { q: "What is Hybrid Inheritance?", options: ["Combination of multiple types of inheritance", "Inheriting from one class", "No inheritance at all", "Static inheritance"], answer: 0 },
        { q: "What is a Friend Function (in C++)?", options: ["A member function", "A non-member function that can access private data", "A static function", "A virtual function"], answer: 1 },
        { q: "What is a Pure Virtual Function?", options: ["A function with = 0 declaration", "A function with a body", "A private function", "A constant function"], answer: 0 },
        { q: "What is Coupling in OOPS?", options: ["Degree of dependence between classes", "Binding data together", "Inheritance depth", "Number of methods"], answer: 0 },
        { q: "What is Cohesion?", options: ["Measure of how related the features within a class are", "Linking two classes", "Visibility of members", "Performance of a class"], answer: 0 },
        { q: "What is an Exception in OOPS?", options: ["A syntax error", "An unexpected event during execution", "A logic error", "A compiled warning"], answer: 1 }
    ],
    os: [
        { q: "An Operating System is effectively:", options: ["An Antivirus program", "A Web Browser", "An interface between user and hardware", "A Compiler"], answer: 2 },
        { q: "What is a process?", options: ["A text file", "A program in execution", "A database record", "A device driver"], answer: 1 },
        { q: "A thread is also known as:", options: ["A Heavyweight process", "A Lightweight process", "A Data structure", "An Array block"], answer: 1 },
        { q: "Which condition is required for a Deadlock?", options: ["Mutual exclusion", "Hold and wait", "No preemption", "All of the above"], answer: 3 },
        { q: "What is demand paging?", options: ["Loading all pages at swap", "Deleting old pages", "Loading pages only when requested", "Swapping disk fragments"], answer: 2 },
        { q: "The FIFO algorithm is commonly associated with:", options: ["Disk formatting", "CPU scheduling", "Page replacement", "Memory allocation"], answer: 2 },
        { q: "What is Virtual Memory?", options: ["Extra RAM", "A technique that allows execution of processes larger than RAM", "A type of cache", "Hard disk space"], answer: 1 },
        { q: "What is Thrashing?", options: ["High CPU utilization", "The system spending more time swapping than executing", "A fast process", "Memory leak"], answer: 1 },
        { q: "What is a System Call?", options: ["A function call within a program", "A way for a program to request services from the OS kernel", "An error message", "A hardware interrupt"], answer: 1 },
        { q: "Which scheduling algorithm can lead to starvation?", options: ["Round Robin", "Priority Scheduling", "FCFS", "SJF"], answer: 1 },
        { q: "What is a Semaphore?", options: ["A hardware device", "A variable used to control access to shared resources", "A type of process", "A memory address"], answer: 1 },
        { q: "What is External Fragmentation?", options: ["Wasted space inside a partition", "Wasted space between partitions", "Disk failure", "File corruption"], answer: 1 },
        { q: "What is Internal Fragmentation?", options: ["Wasted space between partitions", "Wasted space within a memory block", "CPU overheating", "RAM failure"], answer: 1 },
        { q: "What is a Kernel?", options: ["The core of the OS that manages resources", "A user interface", "A browser", "A shell script"], answer: 0 },
        { q: "What is Context Switching?", options: ["Changing user names", "Saving and restoring process state", "Moving files", "Switching between hard drives"], answer: 1 },
        { q: "What is a Shell?", options: ["The OS kernel", "A user interface for access to an operating system's services", "A web browser", "A type of file"], answer: 1 },
        { q: "What is RAID?", options: ["A security protocol", "Redundant Array of Independent Disks", "A virus", "A sorting algorithm"], answer: 1 },
        { q: "What is the purpose of Spooling?", options: ["Printing documents directly", "Overlapping I/O of one job with CPU of another", "Deleting files", "Memory management"], answer: 1 },
        { q: "What is a Daemon?", options: ["A malicious program", "A background process that runs without interactive user control", "A type of driver", "A system error"], answer: 1 },
        { q: "Which of these is a Preemptive Scheduling algorithm?", options: ["FCFS", "SJF (Non-preemptive)", "Round Robin", "HRRN"], answer: 2 },
        { q: "What is Belady's Anomaly?", options: ["More page frames resulting in more page faults", "Less RAM resulting in faster execution", "Infinite loops", "Memory leaks"], answer: 0 },
        { q: "What is paging?", options: ["Allocating non-contiguous memory in fixed-size blocks", "Splitting files into parts", "CPU speed optimization", "Disk cleanup"], answer: 0 },
        { q: "What is segmentation?", options: ["Memory management scheme that supports user view of memory", "Dividing disk into sectors", "CPU cache levels", "Network layers"], answer: 0 },
        { q: "What is the critical section problem?", options: ["Managing shared resources to avoid race conditions", "Finding the best CPU", "Disk failure", "Memory allocation error"], answer: 0 },
        { q: "What is a Mutex?", options: ["A math function", "A mutual exclusion object for thread sync", "A type of memory", "A process ID"], answer: 1 },
        { q: "What is an Interrupt?", options: ["A system crash", "A signal from hardware or software indicating an event needs attention", "A user input", "A loop break"], answer: 1 },
        { q: "What is Throughput?", options: ["Time to finish one job", "Number of processes completed per unit time", "Memory speed", "Data security"], answer: 1 },
        { q: "What is Response Time?", options: ["Time taken from request submission until first response", "Total time to execute a process", "Wait time in queue", "Disk access time"], answer: 0 },
        { q: "What is a Trap?", options: ["A hardware error", "A software-generated interrupt", "A security breach", "A loop"], answer: 1 },
        { q: "What is the main task of the Dispatcher?", options: ["Scheduling processes", "Giving control of the CPU to the process selected by the short-term scheduler", "Memory allocation", "Resource cleanup"], answer: 1 }
    ],
    cn: [
        { q: "Which protocol operates at the Transport Layer?", options: ["TCP", "IP", "HTTP", "FTP"], answer: 0 },
        { q: "What is the length of an IPv4 address?", options: ["16 bits", "32 bits", "64 bits", "128 bits"], answer: 1 },
        { q: "What is the standard size of a MAC address?", options: ["24 bits", "32 bits", "48 bits", "64 bits"], answer: 2 },
        { q: "What is the function of DNS?", options: ["Transfers files", "Sends emails", "Secures data", "Resolves domain names to IP addresses"], answer: 3 },
        { q: "Which network topology uses a central hub?", options: ["Star", "Ring", "Bus", "Mesh"], answer: 0 },
        { q: "How many layers are in the OSI model?", options: ["4", "5", "6", "7"], answer: 3 },
        { q: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "HighText Transfer Process", "Hyperlink Text Transmission", "HyperText Total Protocol"], answer: 0 },
        { q: "What is the purpose of the ARP protocol?", options: ["Map IP to MAC address", "Assign IP addresses", "Domain resolution", "Email transfer"], answer: 0 },
        { q: "ICMP protocol is primarily used for:", options: ["File transfer", "Error reporting and diagnostics", "Web browsing", "Data encryption"], answer: 1 },
        { q: "Which layer of the OSI model handles data compression?", options: ["Application", "Presentation", "Session", "Transport"], answer: 1 },
        { q: "What is a Firewall?", options: ["A cooling system", "A network security system", "A fast router", "A backup storage"], answer: 1 },
        { q: "What is the default port for HTTPS?", options: ["80", "21", "443", "53"], answer: 2 },
        { q: "What does DHCP stand for?", options: ["Dynamic Host Configuration Protocol", "Data Handling Communication Process", "Direct Host Connection Protocol", "Domain Host Control Process"], answer: 0 },
        { q: "What is the function of a Hub?", options: ["Intelligent routing", "Broadcasting incoming data to all ports", "Filtering traffic", "Security gateway"], answer: 1 },
        { q: "What is the difference between a Hub and a Switch?", options: ["Switch broadcasts, Hub directs", "Hub is faster", "Switch learns MAC addresses and sends data to specific port", "There is no difference"], answer: 2 },
        { q: "Which layer is responsible for logical addressing?", options: ["Physical", "Data Link", "Network", "Transport"], answer: 2 },
        { q: "What is the purpose of a Router?", options: ["Connecting different networks", "Connecting computers in a LAN", "Charging devices", "Printing documents"], answer: 0 },
        { q: "What is the maximum length of an IPv6 address?", options: ["32 bits", "64 bits", "128 bits", "256 bits"], answer: 2 },
        { q: "What does LAN stand for?", options: ["Local Area Network", "Long Area Network", "Link Area Node", "Large Area Network"], answer: 0 },
        { q: "What is the purpose of SSH?", options: ["Secure file storage", "Secure shell for remote access", "Sending emails", "Website hosting"], answer: 1 },
        { q: "Which protocol is connection-oriented?", options: ["UDP", "TCP", "IP", "ICMP"], answer: 1 },
        { q: "Which protocol is connectionless?", options: ["TCP", "UDP", "HTTP", "FTP"], answer: 1 },
        { q: "What is the default port for FTP?", options: ["21", "22", "23", "25"], answer: 0 },
        { q: "What is the default port for SMTP?", options: ["80", "443", "25", "110"], answer: 2 },
        { q: "What is BGP used for?", options: ["Routing within an AS", "Routing between Autonomous Systems on the internet", "Local network setup", "File transfer"], answer: 1 },
        { q: "What is a Subnet Mask?", options: ["A security key", "A number that defines the range of IP addresses in a network", "A hardware address", "A domain name"], answer: 1 },
        { q: "What is NAT?", options: ["Network Address Translation", "Network Access Tool", "Node Application Tool", "Network Authentication Technique"], answer: 0 },
        { q: "What is the purpose of the Session layer?", options: ["Data encryption", "Managing and terminating sessions", "Routing", "Physical transmission"], answer: 1 },
        { q: "What is Latency in a network?", options: ["Data speed", "The delay before a transfer of data begins", "Security level", "Data loss"], answer: 1 },
        { q: "What is Packet Sniffing?", options: ["Cleaning the network", "Monitoring every packet that crosses a network", "Blocking traffic", "Sending viruses"], answer: 1 }
    ],
    dsa: [
        { q: "Which data structure follows the LIFO principle?", options: ["Queue", "Stack", "Tree", "Graph"], answer: 1 },
        { q: "What is the time complexity of Binary Search?", options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"], answer: 0 },
        { q: "How are standard array elements stored in memory?", options: ["In linked nodes", "In a tree structure", "In non-contiguous memory", "In contiguous memory locations"], answer: 3 },
        { q: "The FIFO principle is utilized in a:", options: ["Stack", "Queue", "Array", "Linked List"], answer: 1 },
        { q: "Which of the following is NOT a linear data structure?", options: ["Tree", "Array", "Linked List", "Stack"], answer: 0 },
        { q: "Quick sort uses which standard algorithmic technique?", options: ["Greedy", "Dynamic Programming", "Divide and Conquer", "Backtracking"], answer: 2 },
        { q: "What is the worst-case time complexity of Bubble Sort?", options: ["O(n)", "O(n log n)", "O(n^2)", "O(1)"], answer: 2 },
        { q: "What is the time complexity to insert an element at the beginning of a Singly Linked List?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 0 },
        { q: "What is the time complexity to search an element in a Hash Table (average case)?", options: ["O(n)", "O(log n)", "O(1)", "O(n log n)"], answer: 2 },
        { q: "A binary tree in which every node has either 0 or 2 children is called:", options: ["Complete Binary Tree", "Full Binary Tree", "Perfect Binary Tree", "Balanced Binary Tree"], answer: 1 },
        { q: "Which of the following traversal techniques visits the root node first?", options: ["In-order", "Pre-order", "Post-order", "Level-order"], answer: 1 },
        { q: "A graph with no cycles is called:", options: ["Directed Graph", "Acyclic Graph", "Complete Graph", "Connected Graph"], answer: 1 },
        { q: "Dijkstra's algorithm is used for:", options: ["Sorting", "Finding the shortest path from a single source", "Finding minimum spanning tree", "Graph coloring"], answer: 1 },
        { q: "What is the auxiliary space complexity of Merge Sort?", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], answer: 1 },
        { q: "Which data structure is best for implementing a priority queue?", options: ["Stack", "Queue", "Heap", "Linked List"], answer: 2 },
        { q: "Post-order traversal of a tree visits the root:", options: ["First", "In the middle", "Last", "Never"], answer: 2 },
        { q: "What is the height of a balanced binary search tree with n nodes?", options: ["O(n)", "O(log n)", "O(sqrt(n))", "O(1)"], answer: 1 },
        { q: "Which sorting algorithm is stable?", options: ["Quick Sort", "Merge Sort", "Heap Sort", "Selection Sort"], answer: 1 },
        { q: "What is a circular linked list?", options: ["A list where the last node points to the first", "A list with no nodes", "A doubly linked list", "A list with a cycle in the middle"], answer: 0 },
        { q: "Which algorithm is used for pattern searching in strings?", options: ["Kruskal's", "Prim's", "Knuth-Morris-Pratt (KMP)", "Bellman-Ford"], answer: 2 },
        { q: "What is a Minimum Spanning Tree (MST)?", options: ["A subset of edges connecting all vertices with minimum total weight", "The shortest path between two nodes", "A graph with maximum edges", "A tree with minimum height"], answer: 0 },
        { q: "Kruskal's algorithm uses which approach?", options: ["Dynamic Programming", "Greedy", "Backtracking", "Divide and Conquer"], answer: 1 },
        { q: "Which data structure is used in BFS (Breadth-First Search)?", options: ["Stack", "Queue", "Priority Queue", "Array"], answer: 1 },
        { q: "Which data structure is used in DFS (Depth-First Search)?", options: ["Queue", "Priority Queue", "Stack", "Linked List"], answer: 2 },
        { q: "What is a Collision in a Hash Table?", options: ["When two keys hash to the same index", "When the table is full", "When memory leaks", "When a key is not found"], answer: 0 },
        { q: "What is an AVL tree?", options: ["A self-balancing binary search tree", "A type of heap", "A graph representation", "A linear data structure"], answer: 0 },
        { q: "What is the time complexity of building a heap from an array of size n?", options: ["O(n log n)", "O(n)", "O(log n)", "O(1)"], answer: 1 },
        { q: "Which of the following is NOT a comparison-based sorting algorithm?", options: ["Quick Sort", "Insertion Sort", "Radix Sort", "Merge Sort"], answer: 2 },
        { q: "What is the space complexity of a recursive implementation of DFS?", options: ["O(V+E)", "O(V)", "O(log V)", "O(E)"], answer: 1 },
        { q: "Which data structure is most efficient to check if a word is in a dictionary?", options: ["Linked List", "Trie", "Stack", "Queue"], answer: 1 }
    ]
};
